# Generated by Django 5.0.7 on 2024-07-13 03:52

from django.db import migrations
class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_user_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
